# --- SERVER CONFIGURATION ---
SERVER_PORT=7088
SPRING_PROFILES_ACTIVE=dev

# --- POSTGRES DATABASE ---
# Format: jdbc:postgresql://<host>:<port>/<database_name>
SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5433/object_storage_backend
SPRING_DATASOURCE_USERNAME=postgres
SPRING_DATASOURCE_PASSWORD=postgres

# --- FLYWAY MIGRATIONS ---
# These are used by the flyway-maven-plugin
FLYWAY_URL=${SPRING_DATASOURCE_URL}
FLYWAY_USER=${SPRING_DATASOURCE_USERNAME}
FLYWAY_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

# --- REDIS CONFIGURATION ---
SPRING_DATA_REDIS_HOST=localhost
SPRING_DATA_REDIS_PORT=6379
# --- SECURITY / JWT ---
# Generate a secure 256-bit key for signing tokens
JWT_SECRET=your_super_secret_key_at_least_32_characters_long
JWT_EXPIRATION_MS=86400000



NOVU_ENABLED=true
NOVU_API_KEY=4c88e4251e4e3378f8721a79d7b70efc
NOVU_BASE_URL=https://api.novu.co/v1


APP_BASE_URL=http://localhost:7088

host: localhost
port: 6379